CREATE TABLE Organisation
(
 organisation_id               int          not null PRIMARY KEY identity,
 entity_id                     int          not null FOREIGN KEY REFERENCES Entity(entity_id) UNIQUE,
 parent_organisation_id        int                   FOREIGN KEY REFERENCES Organisation(organisation_id) DEFAULT null,
 use_parent_offernig_prices    bit          not null,
 organisation_type_id          int          not null FOREIGN KEY REFERENCES OrganisationType(organisation_type_id),
 organisation_customer_type_id int          not null FOREIGN KEY REFERENCES OrganisationCustomerType(organisation_customer_type_id),
 name                          varchar(100) not null,
 acn                           varchar(50)  not null,
 abn                           varchar(50)  not null,
 organisation_date_added       datetime     not null DEFAULT (GETDATE()),
 organisation_date_modified    datetime              DEFAULT null,
 is_debtor                     bit          not null,
 is_creditor                   bit          not null,
 bpay_account                  varchar(50)  not null,
 is_deleted                    bit          not null DEFAULT 0,           -- if logically deleted from system but still exists in system

 weeks_per_service_cycle int    not null,
 start_date                    datetime              DEFAULT null,   -- was:   start_date        datetime     not null DEFAULT (GETDATE()),
 end_date                      datetime              DEFAULT null,
 comment                       varchar(max) not null,
 free_services                 int          not null,
 excl_sun                      bit          not null,
 excl_mon                      bit          not null,
 excl_tue                      bit          not null,
 excl_wed                      bit          not null,
 excl_thu                      bit          not null,
 excl_fri                      bit          not null,
 excl_sat                      bit          not null,
 sun_start_time                time         not null,
 sun_end_time                  time         not null,
 mon_start_time                time         not null,
 mon_end_time                  time         not null,
 tue_start_time                time         not null,
 tue_end_time                  time         not null,
 wed_start_time                time         not null,
 wed_end_time                  time         not null,
 thu_start_time                time         not null,
 thu_end_time                  time         not null,
 fri_start_time                time         not null,
 fri_end_time                  time         not null,
 sat_start_time                time         not null,
 sat_end_time                  time         not null,

 sun_lunch_start_time          time         not null,
 sun_lunch_end_time            time         not null,
 mon_lunch_start_time          time         not null,
 mon_lunch_end_time            time         not null,
 tue_lunch_start_time          time         not null,
 tue_lunch_end_time            time         not null,
 wed_lunch_start_time          time         not null,
 wed_lunch_end_time            time         not null,
 thu_lunch_start_time          time         not null,
 thu_lunch_end_time            time         not null,
 fri_lunch_start_time          time         not null,
 fri_lunch_end_time            time         not null,
 sat_lunch_start_time          time         not null,
 sat_lunch_end_time            time         not null,

 last_batch_run                datetime               DEFAULT null,
);
