CREATE TABLE Country
(
 country_id             int          not null PRIMARY KEY identity,
 descr                  varchar(50) not null,
);


SET IDENTITY_INSERT Country ON;
INSERT Country
  (country_id,descr)
VALUES
  (3,'NEW ZEALAND'),
  (40,'UNITED KINGDOM'),
  (44,'AUSTRALIA'),
  (167,'UNITES STATES');
SET IDENTITY_INSERT Country OFF;


INSERT Country
  (descr)
VALUES
  (UPPER('Afghanistan')),
  (UPPER('Albania')),
  (UPPER('Algeria')),
  (UPPER('American Samoa')),
  (UPPER('Andorra')),
  (UPPER('Angola')),
  (UPPER('Anguilla')),
  (UPPER('Antigua and Barbuda')),
  (UPPER('Argentina')),
  (UPPER('Armenia')),
  (UPPER('Aruba')),
--  (UPPER('Australia')),
  (UPPER('Austria')),
  (UPPER('Azerbaijan')),
  (UPPER('Bahamas')),
  (UPPER('Bahrain')),
  (UPPER('Bangladesh')),
  (UPPER('Barbados')),
  (UPPER('Belarus')),
  (UPPER('Belgium')),
  (UPPER('Belize')),
  (UPPER('Benin')),
  (UPPER('Bermuda')),
  (UPPER('Bhutan')),
  (UPPER('Bolivia')),
  (UPPER('Bosnia-Herzegovina')),
  (UPPER('Botswana')),
  (UPPER('Bouvet Island')),
  (UPPER('Brazil')),
  (UPPER('Brunei')),
  (UPPER('Bulgaria')),
  (UPPER('Burkina Faso')),
  (UPPER('Burundi')),
  (UPPER('Cambodia')),
  (UPPER('Cameroon')),
  (UPPER('Canada')),
  (UPPER('Cape Verde')),
  (UPPER('Cayman Islands')),
  (UPPER('Central African Republic')),
  (UPPER('Chad')),
  (UPPER('Chile')),
  (UPPER('China')),
  (UPPER('Christmas Island')),
  (UPPER('Cocos (Keeling) Islands')),
  (UPPER('Colombia')),
  (UPPER('Comoros')),
  (UPPER('Congo, Democratic Republic of the (Zaire)')),
  (UPPER('Congo, Republic of')),
  (UPPER('Cook Islands')),
  (UPPER('Costa Rica')),
  (UPPER('Croatia')),
  (UPPER('Cuba')),
  (UPPER('Cyprus')),
  (UPPER('Czech Republic')),
  (UPPER('Denmark')),
  (UPPER('Djibouti')),
  (UPPER('Dominica')),
  (UPPER('Dominican Republic')),
  (UPPER('Ecuador')),
  (UPPER('Egypt')),
  (UPPER('El Salvador')),
  (UPPER('Equatorial Guinea')),
  (UPPER('Eritrea')),
  (UPPER('Estonia')),
  (UPPER('Ethiopia')),
  (UPPER('Falkland Islands')),
  (UPPER('Faroe Islands')),
  (UPPER('Fiji')),
  (UPPER('Finland')),
  (UPPER('France')),
  (UPPER('French Guiana')),
  (UPPER('Gabon')),
  (UPPER('Gambia')),
  (UPPER('Georgia')),
  (UPPER('Germany')),
  (UPPER('Ghana')),
  (UPPER('Gibraltar')),
  (UPPER('Greece')),
  (UPPER('Greenland')),
  (UPPER('Grenada')),
  (UPPER('Guadeloupe (French)')),
  (UPPER('Guam (USA)')),
  (UPPER('Guatemala')),
  (UPPER('Guinea')),
  (UPPER('Guinea Bissau')),
  (UPPER('Guyana')),
  (UPPER('Haiti')),
  (UPPER('Holy See')),
  (UPPER('Honduras')),
  (UPPER('Hong Kong')),
  (UPPER('Hungary')),
  (UPPER('Iceland')),
  (UPPER('India')),
  (UPPER('Indonesia')),
  (UPPER('Iran')),
  (UPPER('Iraq')),
  (UPPER('Ireland')),
  (UPPER('Israel')),
  (UPPER('Italy')),
  (UPPER('Ivory Coast (Cote D`Ivoire)')),
  (UPPER('Jamaica')),
  (UPPER('Japan')),
  (UPPER('Jordan')),
  (UPPER('Kazakhstan')),
  (UPPER('Kenya')),
  (UPPER('Kiribati')),
  (UPPER('Kuwait')),
  (UPPER('Kyrgyzstan')),
  (UPPER('Laos')),
  (UPPER('Latvia')),
  (UPPER('Lebanon')),
  (UPPER('Lesotho')),
  (UPPER('Liberia')),
  (UPPER('Libya')),
  (UPPER('Liechtenstein')),
  (UPPER('Lithuania')),
  (UPPER('Luxembourg')),
  (UPPER('Macau')),
  (UPPER('Macedonia')),
  (UPPER('Madagascar')),
  (UPPER('Malawi')),
  (UPPER('Malaysia')),
  (UPPER('Maldives')),
  (UPPER('Mali')),
  (UPPER('Malta')),
  (UPPER('Marshall Islands')),
  (UPPER('Martinique (French)')),
  (UPPER('Mauritania')),
  (UPPER('Mauritius')),
  (UPPER('Mayotte')),
  (UPPER('Mexico')),
  (UPPER('Micronesia')),
  (UPPER('Moldova')),
  (UPPER('Monaco')),
  (UPPER('Mongolia')),
  (UPPER('Montenegro')),
  (UPPER('Montserrat')),
  (UPPER('Morocco')),
  (UPPER('Mozambique')),
  (UPPER('Myanmar')),
  (UPPER('Namibia')),
  (UPPER('Nauru')),
  (UPPER('Nepal')),
  (UPPER('Netherlands')),
  (UPPER('Netherlands Antilles')),
  (UPPER('New Caledonia (French)')),
--  (UPPER('New Zealand')),
  (UPPER('Nicaragua')),
  (UPPER('Niger')),
  (UPPER('Nigeria')),
  (UPPER('Niue')),
  (UPPER('Norfolk Island')),
  (UPPER('North Korea')),
  (UPPER('Northern Mariana Islands')),
  (UPPER('Norway')),
  (UPPER('Oman')),
  (UPPER('Pakistan')),
  (UPPER('Palau')),
  (UPPER('Panama')),
  (UPPER('Papua New Guinea')),
  (UPPER('Paraguay')),
  (UPPER('Peru')),
  (UPPER('Philippines')),
  (UPPER('Pitcairn Island')),
  (UPPER('Poland')),
  (UPPER('Polynesia (French)')),
  (UPPER('Portugal')),
  (UPPER('Puerto Rico')),
  (UPPER('Qatar')),
  (UPPER('Reunion')),
  (UPPER('Romania')),
  (UPPER('Russia')),
  (UPPER('Rwanda')),
  (UPPER('Saint Helena')),
  (UPPER('Saint Kitts and Nevis')),
  (UPPER('Saint Lucia')),
  (UPPER('Saint Pierre and Miquelon')),
  (UPPER('Saint Vincent and Grenadines')),
  (UPPER('Samoa')),
  (UPPER('San Marino')),
  (UPPER('Sao Tome and Principe')),
  (UPPER('Saudi Arabia')),
  (UPPER('Senegal')),
  (UPPER('Serbia')),
  (UPPER('Seychelles')),
  (UPPER('Sierra Leone')),
  (UPPER('Singapore')),
  (UPPER('Slovakia')),
  (UPPER('Slovenia')),
  (UPPER('Solomon Islands')),
  (UPPER('Somalia')),
  (UPPER('South Africa')),
  (UPPER('South Georgia and South Sandwich Islands')),
  (UPPER('South Korea')),
  (UPPER('Spain')),
  (UPPER('Sri Lanka')),
  (UPPER('Sudan')),
  (UPPER('Suriname')),
  (UPPER('Svalbard and Jan Mayen Islands')),
  (UPPER('Swaziland')),
  (UPPER('Sweden')),
  (UPPER('Switzerland')),
  (UPPER('Syria')),
  (UPPER('Taiwan')),
  (UPPER('Tajikistan')),
  (UPPER('Tanzania')),
  (UPPER('Thailand')),
  (UPPER('Timor-Leste (East Timor)')),
  (UPPER('Togo')),
  (UPPER('Tokelau')),
  (UPPER('Tonga')),
  (UPPER('Trinidad and Tobago')),
  (UPPER('Tunisia')),
  (UPPER('Turkey')),
  (UPPER('Turkmenistan')),
  (UPPER('Turks and Caicos Islands')),
  (UPPER('Tuvalu')),
  (UPPER('Uganda')),
  (UPPER('Ukraine')),
  (UPPER('United Arab Emirates')),
--  (UPPER('United Kingdom')),
--  (UPPER('United States')),
  (UPPER('Uruguay')),
  (UPPER('Uzbekistan')),
  (UPPER('Vanuatu')),
  (UPPER('Venezuela')),
  (UPPER('Vietnam')),
  (UPPER('Virgin Islands')),
  (UPPER('Wallis and Futuna Islands')),
  (UPPER('Yemen')),
  (UPPER('Zambia')),
  (UPPER('Zimbabwe'));
