//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://px.ezidebit.com.au/", ClrNamespace="px.ezidebit.com.au")]

namespace px.ezidebit.com.au
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfNewCustomerXcXH3liW", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfNewCustomerXcXH3liW : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ezidebit.PaymentExchange.V3_3.DataContracts.NewCustomer DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ezidebit.PaymentExchange.V3_3.DataContracts.NewCustomer Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfstring", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfstring : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfCustomerDetailsTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfCustomerDetailsTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.CustomerDetails DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.CustomerDetails Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDetails", Namespace="https://px.ezidebit.com.au/")]
    public partial class CustomerDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string AddressPostCodeField;
        
        private string AddressStateField;
        
        private string AddressSuburbField;
        
        private System.Nullable<System.DateTime> ContractStartDateField;
        
        private string CustomerFirstNameField;
        
        private string CustomerNameField;
        
        private string EmailField;
        
        private string EzidebitCustomerIDField;
        
        private string MobilePhoneField;
        
        private string PaymentMethodField;
        
        private string PaymentPeriodField;
        
        private string PaymentPeriodDayOfMonthField;
        
        private string PaymentPeriodDayOfWeekField;
        
        private string SmsExpiredCardField;
        
        private string SmsFailedNotificationField;
        
        private string SmsPaymentReminderField;
        
        private string StatusCodeField;
        
        private string StatusDescriptionField;
        
        private int TotalPaymentsFailedField;
        
        private double TotalPaymentsFailedAmountField;
        
        private int TotalPaymentsSuccessfulField;
        
        private double TotalPaymentsSuccessfulAmountField;
        
        private string YourGeneralReferenceField;
        
        private string YourSystemReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressPostCode
        {
            get
            {
                return this.AddressPostCodeField;
            }
            set
            {
                this.AddressPostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressState
        {
            get
            {
                return this.AddressStateField;
            }
            set
            {
                this.AddressStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressSuburb
        {
            get
            {
                return this.AddressSuburbField;
            }
            set
            {
                this.AddressSuburbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractStartDate
        {
            get
            {
                return this.ContractStartDateField;
            }
            set
            {
                this.ContractStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName
        {
            get
            {
                return this.CustomerFirstNameField;
            }
            set
            {
                this.CustomerFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EzidebitCustomerID
        {
            get
            {
                return this.EzidebitCustomerIDField;
            }
            set
            {
                this.EzidebitCustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone
        {
            get
            {
                return this.MobilePhoneField;
            }
            set
            {
                this.MobilePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentPeriod
        {
            get
            {
                return this.PaymentPeriodField;
            }
            set
            {
                this.PaymentPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentPeriodDayOfMonth
        {
            get
            {
                return this.PaymentPeriodDayOfMonthField;
            }
            set
            {
                this.PaymentPeriodDayOfMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentPeriodDayOfWeek
        {
            get
            {
                return this.PaymentPeriodDayOfWeekField;
            }
            set
            {
                this.PaymentPeriodDayOfWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsExpiredCard
        {
            get
            {
                return this.SmsExpiredCardField;
            }
            set
            {
                this.SmsExpiredCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsFailedNotification
        {
            get
            {
                return this.SmsFailedNotificationField;
            }
            set
            {
                this.SmsFailedNotificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsPaymentReminder
        {
            get
            {
                return this.SmsPaymentReminderField;
            }
            set
            {
                this.SmsPaymentReminderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPaymentsFailed
        {
            get
            {
                return this.TotalPaymentsFailedField;
            }
            set
            {
                this.TotalPaymentsFailedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPaymentsFailedAmount
        {
            get
            {
                return this.TotalPaymentsFailedAmountField;
            }
            set
            {
                this.TotalPaymentsFailedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPaymentsSuccessful
        {
            get
            {
                return this.TotalPaymentsSuccessfulField;
            }
            set
            {
                this.TotalPaymentsSuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPaymentsSuccessfulAmount
        {
            get
            {
                return this.TotalPaymentsSuccessfulAmountField;
            }
            set
            {
                this.TotalPaymentsSuccessfulAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourGeneralReference
        {
            get
            {
                return this.YourGeneralReferenceField;
            }
            set
            {
                this.YourGeneralReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourSystemReference
        {
            get
            {
                return this.YourSystemReferenceField;
            }
            set
            {
                this.YourSystemReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfArrayOfScheduledPaymentTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfArrayOfScheduledPaymentTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.ScheduledPayment[] DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.ScheduledPayment[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledPayment", Namespace="https://px.ezidebit.com.au/")]
    public partial class ScheduledPayment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EzidebitCustomerIDField;
        
        private bool ManuallyAddedPaymentField;
        
        private double PaymentAmountField;
        
        private System.DateTime PaymentDateField;
        
        private string PaymentReferenceField;
        
        private string YourGeneralReferenceField;
        
        private string YourSystemReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EzidebitCustomerID
        {
            get
            {
                return this.EzidebitCustomerIDField;
            }
            set
            {
                this.EzidebitCustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ManuallyAddedPayment
        {
            get
            {
                return this.ManuallyAddedPaymentField;
            }
            set
            {
                this.ManuallyAddedPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference
        {
            get
            {
                return this.PaymentReferenceField;
            }
            set
            {
                this.PaymentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourGeneralReference
        {
            get
            {
                return this.YourGeneralReferenceField;
            }
            set
            {
                this.YourGeneralReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourSystemReference
        {
            get
            {
                return this.YourSystemReferenceField;
            }
            set
            {
                this.YourSystemReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfPaymentDetailTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfPaymentDetailTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.PaymentDetail DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.PaymentDetail Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDetail", Namespace="https://px.ezidebit.com.au/")]
    public partial class PaymentDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BankFailedReasonField;
        
        private string BankReturnCodeField;
        
        private System.DateTime DebitDateField;
        
        private string InvoiceIDField;
        
        private double PaymentAmountField;
        
        private string PaymentIDField;
        
        private string PaymentMethodField;
        
        private string PaymentReferenceField;
        
        private string PaymentStatusField;
        
        private double ScheduledAmountField;
        
        private System.Nullable<System.DateTime> SettlementDateField;
        
        private double TransactionFeeClientField;
        
        private double TransactionFeeCustomerField;
        
        private string YourGeneralReferenceField;
        
        private string YourSystemReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankFailedReason
        {
            get
            {
                return this.BankFailedReasonField;
            }
            set
            {
                this.BankFailedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankReturnCode
        {
            get
            {
                return this.BankReturnCodeField;
            }
            set
            {
                this.BankReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DebitDate
        {
            get
            {
                return this.DebitDateField;
            }
            set
            {
                this.DebitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceID
        {
            get
            {
                return this.InvoiceIDField;
            }
            set
            {
                this.InvoiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference
        {
            get
            {
                return this.PaymentReferenceField;
            }
            set
            {
                this.PaymentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScheduledAmount
        {
            get
            {
                return this.ScheduledAmountField;
            }
            set
            {
                this.ScheduledAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SettlementDate
        {
            get
            {
                return this.SettlementDateField;
            }
            set
            {
                this.SettlementDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TransactionFeeClient
        {
            get
            {
                return this.TransactionFeeClientField;
            }
            set
            {
                this.TransactionFeeClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TransactionFeeCustomer
        {
            get
            {
                return this.TransactionFeeCustomerField;
            }
            set
            {
                this.TransactionFeeCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourGeneralReference
        {
            get
            {
                return this.YourGeneralReferenceField;
            }
            set
            {
                this.YourGeneralReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourSystemReference
        {
            get
            {
                return this.YourSystemReferenceField;
            }
            set
            {
                this.YourSystemReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfPaymentDetailPlusNextPaymentInfoTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfPaymentDetailPlusNextPaymentInfoTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.PaymentDetailPlusNextPaymentInfo DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.PaymentDetailPlusNextPaymentInfo Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDetailPlusNextPaymentInfo", Namespace="https://px.ezidebit.com.au/")]
    public partial class PaymentDetailPlusNextPaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.NextPaymentInfo NextPaymentInfoField;
        
        private px.ezidebit.com.au.PaymentDetail PaymentDetailField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.NextPaymentInfo NextPaymentInfo
        {
            get
            {
                return this.NextPaymentInfoField;
            }
            set
            {
                this.NextPaymentInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.PaymentDetail PaymentDetail
        {
            get
            {
                return this.PaymentDetailField;
            }
            set
            {
                this.PaymentDetailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NextPaymentInfo", Namespace="https://px.ezidebit.com.au/")]
    public partial class NextPaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerStatusCodeField;
        
        private string CustomerStatusDescriptionField;
        
        private double NextPaymentAmountField;
        
        private System.Nullable<System.DateTime> NextPaymentDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerStatusCode
        {
            get
            {
                return this.CustomerStatusCodeField;
            }
            set
            {
                this.CustomerStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerStatusDescription
        {
            get
            {
                return this.CustomerStatusDescriptionField;
            }
            set
            {
                this.CustomerStatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NextPaymentAmount
        {
            get
            {
                return this.NextPaymentAmountField;
            }
            set
            {
                this.NextPaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextPaymentDate
        {
            get
            {
                return this.NextPaymentDateField;
            }
            set
            {
                this.NextPaymentDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfArrayOfPaymentTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfArrayOfPaymentTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.Payment[] DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.Payment[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="https://px.ezidebit.com.au/")]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BankFailedReasonField;
        
        private string BankReceiptIDField;
        
        private string BankReturnCodeField;
        
        private string CustomerNameField;
        
        private System.Nullable<System.DateTime> DebitDateField;
        
        private string EzidebitCustomerIDField;
        
        private string InvoiceIDField;
        
        private double PaymentAmountField;
        
        private string PaymentIDField;
        
        private string PaymentMethodField;
        
        private string PaymentReferenceField;
        
        private string PaymentSourceField;
        
        private string PaymentStatusField;
        
        private double ScheduledAmountField;
        
        private System.Nullable<System.DateTime> SettlementDateField;
        
        private double TransactionFeeClientField;
        
        private double TransactionFeeCustomerField;
        
        private System.Nullable<System.DateTime> TransactionTimeField;
        
        private string YourGeneralReferenceField;
        
        private string YourSystemReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankFailedReason
        {
            get
            {
                return this.BankFailedReasonField;
            }
            set
            {
                this.BankFailedReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankReceiptID
        {
            get
            {
                return this.BankReceiptIDField;
            }
            set
            {
                this.BankReceiptIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankReturnCode
        {
            get
            {
                return this.BankReturnCodeField;
            }
            set
            {
                this.BankReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DebitDate
        {
            get
            {
                return this.DebitDateField;
            }
            set
            {
                this.DebitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EzidebitCustomerID
        {
            get
            {
                return this.EzidebitCustomerIDField;
            }
            set
            {
                this.EzidebitCustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceID
        {
            get
            {
                return this.InvoiceIDField;
            }
            set
            {
                this.InvoiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference
        {
            get
            {
                return this.PaymentReferenceField;
            }
            set
            {
                this.PaymentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentSource
        {
            get
            {
                return this.PaymentSourceField;
            }
            set
            {
                this.PaymentSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScheduledAmount
        {
            get
            {
                return this.ScheduledAmountField;
            }
            set
            {
                this.ScheduledAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SettlementDate
        {
            get
            {
                return this.SettlementDateField;
            }
            set
            {
                this.SettlementDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TransactionFeeClient
        {
            get
            {
                return this.TransactionFeeClientField;
            }
            set
            {
                this.TransactionFeeClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TransactionFeeCustomer
        {
            get
            {
                return this.TransactionFeeCustomerField;
            }
            set
            {
                this.TransactionFeeCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransactionTime
        {
            get
            {
                return this.TransactionTimeField;
            }
            set
            {
                this.TransactionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourGeneralReference
        {
            get
            {
                return this.YourGeneralReferenceField;
            }
            set
            {
                this.YourGeneralReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YourSystemReference
        {
            get
            {
                return this.YourSystemReferenceField;
            }
            set
            {
                this.YourSystemReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EziResponseOfRefundPaymentTHgMB7oL", Namespace="https://px.ezidebit.com.au/")]
    public partial class EziResponseOfRefundPaymentTHgMB7oL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private px.ezidebit.com.au.RefundPayment DataField;
        
        private int ErrorField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public px.ezidebit.com.au.RefundPayment Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundPayment", Namespace="https://px.ezidebit.com.au/")]
    public partial class RefundPayment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> BankReceiptIDField;
        
        private System.Nullable<int> RefundPaymentIDField;
        
        private string RefundResultField;
        
        private string RefundResultCodeField;
        
        private string RefundResultTextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BankReceiptID
        {
            get
            {
                return this.BankReceiptIDField;
            }
            set
            {
                this.BankReceiptIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RefundPaymentID
        {
            get
            {
                return this.RefundPaymentIDField;
            }
            set
            {
                this.RefundPaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundResult
        {
            get
            {
                return this.RefundResultField;
            }
            set
            {
                this.RefundResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundResultCode
        {
            get
            {
                return this.RefundResultCodeField;
            }
            set
            {
                this.RefundResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundResultText
        {
            get
            {
                return this.RefundResultTextField;
            }
            set
            {
                this.RefundResultTextField = value;
            }
        }
    }
}
namespace Ezidebit.PaymentExchange.V3_3.DataContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewCustomer", Namespace="http://schemas.datacontract.org/2004/07/Ezidebit.PaymentExchange.V3_3.DataContrac" +
        "ts")]
    public partial class NewCustomer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerRefField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerRef
        {
            get
            {
                return this.CustomerRefField;
            }
            set
            {
                this.CustomerRefField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://px.ezidebit.com.au/", ConfigurationName="INonPCIService")]
public interface INonPCIService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/AddCustomer", ReplyAction="https://px.ezidebit.com.au/INonPCIService/AddCustomerResponse")]
    px.ezidebit.com.au.EziResponseOfNewCustomerXcXH3liW AddCustomer(
                string DigitalKey, 
                string YourSystemReference, 
                string YourGeneralReference, 
                string LastName, 
                string FirstName, 
                string AddressLine1, 
                string AddressLine2, 
                string AddressSuburb, 
                string AddressState, 
                string AddressPostCode, 
                string EmailAddress, 
                string MobilePhoneNumber, 
                string ContractStartDate, 
                string SmsPaymentReminder, 
                string SmsFailedNotification, 
                string SmsExpiredCard, 
                string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/EditCustomerDetails", ReplyAction="https://px.ezidebit.com.au/INonPCIService/EditCustomerDetailsResponse")]
    px.ezidebit.com.au.EziResponseOfstring EditCustomerDetails(
                string DigitalKey, 
                string EziDebitCustomerID, 
                string YourSystemReference, 
                string NewYourSystemReference, 
                string YourGeneralReference, 
                string LastName, 
                string FirstName, 
                string AddressLine1, 
                string AddressLine2, 
                string AddressSuburb, 
                string AddressState, 
                string AddressPostCode, 
                string EmailAddress, 
                string MobilePhoneNumber, 
                string SmsPaymentReminder, 
                string SmsFailedNotification, 
                string SmsExpiredCard, 
                string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/ChangeCustomerStatus", ReplyAction="https://px.ezidebit.com.au/INonPCIService/ChangeCustomerStatusResponse")]
    px.ezidebit.com.au.EziResponseOfstring ChangeCustomerStatus(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string NewStatus, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetCustomerDetails", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetCustomerDetailsResponse")]
    px.ezidebit.com.au.EziResponseOfCustomerDetailsTHgMB7oL GetCustomerDetails(string DigitalKey, string EziDebitCustomerID, string YourSystemReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/AddPayment", ReplyAction="https://px.ezidebit.com.au/INonPCIService/AddPaymentResponse")]
    px.ezidebit.com.au.EziResponseOfstring AddPayment(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string DebitDate, long PaymentAmountInCents, string PaymentReference, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/DeletePayment", ReplyAction="https://px.ezidebit.com.au/INonPCIService/DeletePaymentResponse")]
    px.ezidebit.com.au.EziResponseOfstring DeletePayment(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string PaymentReference, string DebitDate, long PaymentAmountInCents, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetScheduledPayments", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetScheduledPaymentsResponse")]
    px.ezidebit.com.au.EziResponseOfArrayOfScheduledPaymentTHgMB7oL GetScheduledPayments(string DigitalKey, string DateFrom, string DateTo, string EziDebitCustomerID, string YourSystemReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetPaymentStatus", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetPaymentStatusResponse")]
    px.ezidebit.com.au.EziResponseOfstring GetPaymentStatus(string DigitalKey, string PaymentReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetPaymentDetail", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetPaymentDetailResponse")]
    px.ezidebit.com.au.EziResponseOfPaymentDetailTHgMB7oL GetPaymentDetail(string DigitalKey, string PaymentReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetPaymentDetailPlusNextPaymentInfo", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetPaymentDetailPlusNextPaymentInfoResp" +
        "onse")]
    px.ezidebit.com.au.EziResponseOfPaymentDetailPlusNextPaymentInfoTHgMB7oL GetPaymentDetailPlusNextPaymentInfo(string DigitalKey, string PaymentReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/GetPayments", ReplyAction="https://px.ezidebit.com.au/INonPCIService/GetPaymentsResponse")]
    px.ezidebit.com.au.EziResponseOfArrayOfPaymentTHgMB7oL GetPayments(string DigitalKey, string PaymentType, string PaymentMethod, string PaymentSource, string PaymentReference, string DateFrom, string DateTo, string DateField, string EziDebitCustomerID, string YourSystemReference);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/ChangeScheduledAmount", ReplyAction="https://px.ezidebit.com.au/INonPCIService/ChangeScheduledAmountResponse")]
    px.ezidebit.com.au.EziResponseOfstring ChangeScheduledAmount(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, int ChangeFromPaymentNumber, string ChangeFromDate, long NewPaymentAmountInCents, string ApplyToAllFuturePayments, string KeepManualPayments, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/CreateSchedule", ReplyAction="https://px.ezidebit.com.au/INonPCIService/CreateScheduleResponse")]
    px.ezidebit.com.au.EziResponseOfstring CreateSchedule(
                string DigitalKey, 
                string EziDebitCustomerID, 
                string YourSystemReference, 
                string ScheduleStartDate, 
                string SchedulePeriodType, 
                string DayOfWeek, 
                int DayOfMonth, 
                string FirstWeekOfMonth, 
                string SecondWeekOfMonth, 
                string ThirdWeekOfMonth, 
                string FourthWeekOfMonth, 
                long PaymentAmountInCents, 
                int LimitToNumberOfPayments, 
                long LimitToTotalAmountInCents, 
                string KeepManualPayments, 
                string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/ClearSchedule", ReplyAction="https://px.ezidebit.com.au/INonPCIService/ClearScheduleResponse")]
    px.ezidebit.com.au.EziResponseOfstring ClearSchedule(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string KeepManualPayments, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/ChangeScheduledDate", ReplyAction="https://px.ezidebit.com.au/INonPCIService/ChangeScheduledDateResponse")]
    px.ezidebit.com.au.EziResponseOfstring ChangeScheduledDate(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string ChangeFromDate, string PaymentReference, string ChangeToDate, string KeepManualPayments, string Username);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/TestFunction", ReplyAction="https://px.ezidebit.com.au/INonPCIService/TestFunctionResponse")]
    px.ezidebit.com.au.EziResponseOfstring TestFunction(string ParameterToTest);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/IsBsbValid", ReplyAction="https://px.ezidebit.com.au/INonPCIService/IsBsbValidResponse")]
    px.ezidebit.com.au.EziResponseOfstring IsBsbValid(string DigitalKey, string BankAccountBSB);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/IsSystemLocked", ReplyAction="https://px.ezidebit.com.au/INonPCIService/IsSystemLockedResponse")]
    px.ezidebit.com.au.EziResponseOfstring IsSystemLocked(string DigitalKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/PaymentExchangeVersion", ReplyAction="https://px.ezidebit.com.au/INonPCIService/PaymentExchangeVersionResponse")]
    px.ezidebit.com.au.EziResponseOfstring PaymentExchangeVersion();
    
    [System.ServiceModel.OperationContractAttribute(Action="https://px.ezidebit.com.au/INonPCIService/ProcessRefund", ReplyAction="https://px.ezidebit.com.au/INonPCIService/ProcessRefundResponse")]
    px.ezidebit.com.au.EziResponseOfRefundPaymentTHgMB7oL ProcessRefund(string DigitalKey, string PaymentID, string BankReceiptID, long RefundAmountInCents);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface INonPCIServiceChannel : INonPCIService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class NonPCIServiceClient : System.ServiceModel.ClientBase<INonPCIService>, INonPCIService
{
    
    public NonPCIServiceClient()
    {
    }
    
    public NonPCIServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NonPCIServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NonPCIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NonPCIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public px.ezidebit.com.au.EziResponseOfNewCustomerXcXH3liW AddCustomer(
                string DigitalKey, 
                string YourSystemReference, 
                string YourGeneralReference, 
                string LastName, 
                string FirstName, 
                string AddressLine1, 
                string AddressLine2, 
                string AddressSuburb, 
                string AddressState, 
                string AddressPostCode, 
                string EmailAddress, 
                string MobilePhoneNumber, 
                string ContractStartDate, 
                string SmsPaymentReminder, 
                string SmsFailedNotification, 
                string SmsExpiredCard, 
                string Username)
    {
        return base.Channel.AddCustomer(DigitalKey, YourSystemReference, YourGeneralReference, LastName, FirstName, AddressLine1, AddressLine2, AddressSuburb, AddressState, AddressPostCode, EmailAddress, MobilePhoneNumber, ContractStartDate, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring EditCustomerDetails(
                string DigitalKey, 
                string EziDebitCustomerID, 
                string YourSystemReference, 
                string NewYourSystemReference, 
                string YourGeneralReference, 
                string LastName, 
                string FirstName, 
                string AddressLine1, 
                string AddressLine2, 
                string AddressSuburb, 
                string AddressState, 
                string AddressPostCode, 
                string EmailAddress, 
                string MobilePhoneNumber, 
                string SmsPaymentReminder, 
                string SmsFailedNotification, 
                string SmsExpiredCard, 
                string Username)
    {
        return base.Channel.EditCustomerDetails(DigitalKey, EziDebitCustomerID, YourSystemReference, NewYourSystemReference, YourGeneralReference, LastName, FirstName, AddressLine1, AddressLine2, AddressSuburb, AddressState, AddressPostCode, EmailAddress, MobilePhoneNumber, SmsPaymentReminder, SmsFailedNotification, SmsExpiredCard, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring ChangeCustomerStatus(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string NewStatus, string Username)
    {
        return base.Channel.ChangeCustomerStatus(DigitalKey, EziDebitCustomerID, YourSystemReference, NewStatus, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfCustomerDetailsTHgMB7oL GetCustomerDetails(string DigitalKey, string EziDebitCustomerID, string YourSystemReference)
    {
        return base.Channel.GetCustomerDetails(DigitalKey, EziDebitCustomerID, YourSystemReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring AddPayment(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string DebitDate, long PaymentAmountInCents, string PaymentReference, string Username)
    {
        return base.Channel.AddPayment(DigitalKey, EziDebitCustomerID, YourSystemReference, DebitDate, PaymentAmountInCents, PaymentReference, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring DeletePayment(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string PaymentReference, string DebitDate, long PaymentAmountInCents, string Username)
    {
        return base.Channel.DeletePayment(DigitalKey, EziDebitCustomerID, YourSystemReference, PaymentReference, DebitDate, PaymentAmountInCents, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfArrayOfScheduledPaymentTHgMB7oL GetScheduledPayments(string DigitalKey, string DateFrom, string DateTo, string EziDebitCustomerID, string YourSystemReference)
    {
        return base.Channel.GetScheduledPayments(DigitalKey, DateFrom, DateTo, EziDebitCustomerID, YourSystemReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring GetPaymentStatus(string DigitalKey, string PaymentReference)
    {
        return base.Channel.GetPaymentStatus(DigitalKey, PaymentReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfPaymentDetailTHgMB7oL GetPaymentDetail(string DigitalKey, string PaymentReference)
    {
        return base.Channel.GetPaymentDetail(DigitalKey, PaymentReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfPaymentDetailPlusNextPaymentInfoTHgMB7oL GetPaymentDetailPlusNextPaymentInfo(string DigitalKey, string PaymentReference)
    {
        return base.Channel.GetPaymentDetailPlusNextPaymentInfo(DigitalKey, PaymentReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfArrayOfPaymentTHgMB7oL GetPayments(string DigitalKey, string PaymentType, string PaymentMethod, string PaymentSource, string PaymentReference, string DateFrom, string DateTo, string DateField, string EziDebitCustomerID, string YourSystemReference)
    {
        return base.Channel.GetPayments(DigitalKey, PaymentType, PaymentMethod, PaymentSource, PaymentReference, DateFrom, DateTo, DateField, EziDebitCustomerID, YourSystemReference);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring ChangeScheduledAmount(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, int ChangeFromPaymentNumber, string ChangeFromDate, long NewPaymentAmountInCents, string ApplyToAllFuturePayments, string KeepManualPayments, string Username)
    {
        return base.Channel.ChangeScheduledAmount(DigitalKey, EziDebitCustomerID, YourSystemReference, ChangeFromPaymentNumber, ChangeFromDate, NewPaymentAmountInCents, ApplyToAllFuturePayments, KeepManualPayments, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring CreateSchedule(
                string DigitalKey, 
                string EziDebitCustomerID, 
                string YourSystemReference, 
                string ScheduleStartDate, 
                string SchedulePeriodType, 
                string DayOfWeek, 
                int DayOfMonth, 
                string FirstWeekOfMonth, 
                string SecondWeekOfMonth, 
                string ThirdWeekOfMonth, 
                string FourthWeekOfMonth, 
                long PaymentAmountInCents, 
                int LimitToNumberOfPayments, 
                long LimitToTotalAmountInCents, 
                string KeepManualPayments, 
                string Username)
    {
        return base.Channel.CreateSchedule(DigitalKey, EziDebitCustomerID, YourSystemReference, ScheduleStartDate, SchedulePeriodType, DayOfWeek, DayOfMonth, FirstWeekOfMonth, SecondWeekOfMonth, ThirdWeekOfMonth, FourthWeekOfMonth, PaymentAmountInCents, LimitToNumberOfPayments, LimitToTotalAmountInCents, KeepManualPayments, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring ClearSchedule(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string KeepManualPayments, string Username)
    {
        return base.Channel.ClearSchedule(DigitalKey, EziDebitCustomerID, YourSystemReference, KeepManualPayments, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring ChangeScheduledDate(string DigitalKey, string EziDebitCustomerID, string YourSystemReference, string ChangeFromDate, string PaymentReference, string ChangeToDate, string KeepManualPayments, string Username)
    {
        return base.Channel.ChangeScheduledDate(DigitalKey, EziDebitCustomerID, YourSystemReference, ChangeFromDate, PaymentReference, ChangeToDate, KeepManualPayments, Username);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring TestFunction(string ParameterToTest)
    {
        return base.Channel.TestFunction(ParameterToTest);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring IsBsbValid(string DigitalKey, string BankAccountBSB)
    {
        return base.Channel.IsBsbValid(DigitalKey, BankAccountBSB);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring IsSystemLocked(string DigitalKey)
    {
        return base.Channel.IsSystemLocked(DigitalKey);
    }
    
    public px.ezidebit.com.au.EziResponseOfstring PaymentExchangeVersion()
    {
        return base.Channel.PaymentExchangeVersion();
    }
    
    public px.ezidebit.com.au.EziResponseOfRefundPaymentTHgMB7oL ProcessRefund(string DigitalKey, string PaymentID, string BankReceiptID, long RefundAmountInCents)
    {
        return base.Channel.ProcessRefund(DigitalKey, PaymentID, BankReceiptID, RefundAmountInCents);
    }
}
