<%@ Page Title="Organisation List" Language="C#" MasterPageFile="~/SiteV2.master" AutoEventWireup="true" CodeFile="OrganisationListV2.aspx.cs" Inherits="OrganisationListV2" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">

    <div class="clearfix">
        <div class="page_title"><span id="lblHeading" runat="server">Organisation List</span></div>
        <div class="main_content_with_header">
            <div class="user_login_form">

                <div class="border_top_bottom">
                        <asp:Label ID="lblSearch" runat="server">Search By Name: </asp:Label><asp:TextBox ID="txtSearchName" runat="server"/>
                        <asp:CheckBox ID="chkSearchOnlyStartWith" runat="server" /> &nbsp;<label for="chkSearchOnlyStartWith" style="font-weight:normal;">starts with</label>
                        <span style="padding-left:20px;">
                            <asp:Button ID="btnSearchName" runat="server" Text="Search" onclick="btnSearchName_Click" />
                            <asp:Button ID="btnClearNameSearch" runat="server" Text="Clear" onclick="btnClearNameSearch_Click" />
                        </span>
                        <span style="padding-left:20px;" class="hiddencol"><asp:CheckBox ID="chkUsePaging" runat="server" AutoPostBack="True" OnCheckedChanged="chkUsePaging_CheckedChanged" Checked="False"/> &nbsp;<label for="chkUsePaging" style="font-weight:normal;">use paging</label> </span>
                        <span style="padding-left:20px;"><asp:CheckBox ID="chkShowDeleted" runat="server" AutoPostBack="True" OnCheckedChanged="chkShowDeleted_CheckedChanged" Checked="False" /> &nbsp;<label id="lblShowDeleted" runat="server" for="chkShowDeleted" style="font-weight:normal;">show deleted</label> </span>
                </div>

                <span id="spn_icons" runat="server">
                    <img src="images/Calendar-icon-24px.png" alt="booking sheet icon" style="margin:0 5px 5px 0;" />BK Sheet
                    <span style="padding-left:50px;"><img src="images/list-icon-24.png" alt="booking list icon" style="margin:0 5px 5px 0;" />BK List</span>
                    <span style="padding-left:50px;"><img src="imagesV2/edit.png" alt="edit icon" style="margin:0 5px 5px 0;" />Edit</span>
                    <span style="padding-left:50px;"><img src="imagesV2/x.png" alt="delete icon" style="margin:0 5px 5px 0;" />Delete</span>
                </span>
            </div>

            <div class="text-center">
                <asp:ValidationSummary ID="ValidationSummaryAdd" runat="server" CssClass="failureNotification" ValidationGroup="ValidationSummaryAdd"/>
                <asp:ValidationSummary ID="ValidationSummaryEdit" runat="server" CssClass="failureNotification" ValidationGroup="ValidationSummaryEdit"/>
                <asp:Label ID="lblErrorMessage" runat="server" ForeColor="Red" CssClass="failureNotification"></asp:Label>
            </div>

            <center>
                <div id="autodivheight" class="divautoheight" style="height:500px;">

                    <asp:GridView ID="GrdOrganisation" runat="server" 
                         AutoGenerateColumns="False" DataKeyNames="organisation_id" 
                         OnRowCancelingEdit="GrdOrganisation_RowCancelingEdit" 
                         OnRowDataBound="GrdOrganisation_RowDataBound" 
                         OnRowEditing="GrdOrganisation_RowEditing" 
                         OnRowUpdating="GrdOrganisation_RowUpdating" ShowFooter="False" 
                         OnRowCommand="GrdOrganisation_RowCommand" 
                         OnRowDeleting="GrdOrganisation_RowDeleting" 
                         OnRowCreated="GrdOrganisation_RowCreated"
                         AllowSorting="True" 
                         OnSorting="GridView_Sorting"
                         RowStyle-VerticalAlign="top"
                         AutoGenerateDeleteButton="False"
                         AllowPaging="True"
                         OnPageIndexChanging="GrdOrganisation_PageIndexChanging"
                         PageSize="15"
                         ClientIDMode="Predictable"
                         CssClass="table table-bordered table-striped table-grid table-grid-top-bottum-padding-normal auto_width block_center">
                         <PagerSettings Mode="NumericFirstLast" FirstPageText="First" PreviousPageText="Previous" NextPageText="Next" LastPageText="Last" />

                        <Columns> 

                            <asp:TemplateField HeaderText="ID"  HeaderStyle-HorizontalAlign="Left" SortExpression="organisation_id"> 
                                <EditItemTemplate> 
                                    <asp:Label ID="lblId" runat="server" Text='<%# Bind("organisation_id") %>'></asp:Label>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblId" runat="server" Text='<%# Bind("organisation_id") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="" ShowHeader="False" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Center"> 
                                <ItemTemplate> 
                                    <asp:HyperLink ID="lnkBookings" runat="server" ImageUrl="~/images/Calendar-icon-24px.png" Text="Booking Sheet" ToolTip="Booking Sheet" />
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="" ShowHeader="False" HeaderStyle-HorizontalAlign="Left" ItemStyle-HorizontalAlign="Center"> 
                                <ItemTemplate> 
                                    <asp:HyperLink ID="lnkBookingList" runat="server" ImageUrl="~/images/list-icon-24.png" Text="Booking List" ToolTip="Booking List" />
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Name" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top" SortExpression="name" ItemStyle-CssClass="text_left"> 
                                <EditItemTemplate> 
                                    <asp:TextBox Width="85%" ID="txtName" runat="server" Text='<%# Bind("name") %>' MaxLength="100"></asp:TextBox> 
                                    <asp:RequiredFieldValidator ID="txtValidateNameRequired" runat="server" CssClass="failureNotification"  
                                        ControlToValidate="txtName" 
                                        ErrorMessage="Name is required."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RequiredFieldValidator>
                                    <asp:RegularExpressionValidator ID="txtValidateNameRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtName"
                                        ValidationExpression="^[0-9a-zA-Z\-\.\s',\(\)\[\]]+$"
                                        ErrorMessage="Name can only be letters, hyphens, comas, brackets, or fullstops."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                </EditItemTemplate> 
                                <FooterTemplate>
                                    <asp:TextBox Width="85%" ID="txtNewName" runat="server" MaxLength="100"></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="txtValidateNewNameRequired" runat="server" CssClass="failureNotification"  
                                        ControlToValidate="txtNewName" 
                                        ErrorMessage="Name is required."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryAdd">*</asp:RequiredFieldValidator>
                                    <asp:RegularExpressionValidator ID="txtValidateNewNameRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtNewName"
                                        ValidationExpression="^[0-9a-zA-Z\-\.\s',\(\)\[\]]+$"
                                        ErrorMessage="Name can only be letters, hyphens, comas, or fullstops."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryAdd">*</asp:RegularExpressionValidator>
                                </FooterTemplate> 
                                <ItemTemplate> 
                                    <asp:HyperLink ID="lnkName" runat="server" Text='<%# Eval("name") %>' NavigateUrl='<%#  String.Format("~/OrganisationDetailV2.aspx?type=view{0}&id={1}",(Request.QueryString["org_type_ids"]==null ? "" : "&org_type_ids="+Request.QueryString["org_type_ids"]),Eval("organisation_id")) %>' ToolTip="Full Edit"  />
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Parent" HeaderStyle-HorizontalAlign="Left" SortExpression="parent_organisation_id" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlParent" runat="server" DataTextField="name" DataValueField="organisation_id"> </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblParent" runat="server" Text='<%# Eval("parent_name") != DBNull.Value ? Eval("parent_name") : "&nbsp;--"  %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewParent" runat="server" DataTextField="name" DataValueField="organisation_id"> </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Use Parent<br />Offernig Prices" HeaderStyle-HorizontalAlign="Left" SortExpression="use_parent_offernig_prices" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlUseParentOffernigPrices" runat="server" SelectedValue='<%# Eval("use_parent_offernig_prices") %>'> 
                                        <asp:ListItem Value="True" Text="Yes"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblUseParentOffernigPrices" runat="server" Text='<%# Eval("use_parent_offernig_prices").ToString()=="True"?"Yes":"No" %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewUseParentOffernigPrices" runat="server">
                                        <asp:ListItem Value="True" Text="Yes" Selected="True"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Debtor" HeaderStyle-HorizontalAlign="Left" SortExpression="is_debtor" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlIsDebtor" runat="server" SelectedValue='<%# Eval("is_debtor") %>'> 
                                        <asp:ListItem Value="True" Text="Yes"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblIsDebtor" runat="server" Text='<%# Eval("is_debtor").ToString()=="True"?"Yes":"No" %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewIsDebtor" runat="server">
                                        <asp:ListItem Value="True" Text="Yes" Selected="True"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Creditor" HeaderStyle-HorizontalAlign="Left" SortExpression="is_creditor" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlIsCreditor" runat="server" SelectedValue='<%# Eval("is_creditor") %>'> 
                                        <asp:ListItem Value="True" Text="Yes"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblIsCreditor" runat="server" Text='<%# Eval("is_creditor").ToString()=="True"?"Yes":"No" %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewIsCreditor" runat="server">
                                        <asp:ListItem Value="True" Text="Yes" Selected="True"></asp:ListItem>
                                        <asp:ListItem Value="False" Text="No"></asp:ListItem>
                                    </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Type" HeaderStyle-HorizontalAlign="Left" SortExpression="organisation_type_id" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlType" runat="server" DataTextField="type_descr" DataValueField="organisation_type_id"> </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblType" runat="server" Text='<%# Eval("type_descr") %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewType" runat="server" DataTextField="descr" DataValueField="organisation_type_id"> </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Customer Type" HeaderStyle-HorizontalAlign="Left" SortExpression="ct_organisation_customer_type_id" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlCustType" runat="server" DataTextField="ct_descr" DataValueField="ct_organisation_customer_type_id"> </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblCustType" runat="server" Text='<%# Eval("ct_descr") %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewCustType" runat="server" DataTextField="descr" DataValueField="organisation_customer_type_id"> </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="ABN" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top" SortExpression="abn"> 
                                <EditItemTemplate> 
                                    <asp:TextBox Width="75%" ID="txtABN" runat="server" Text='<%# Bind("abn") %>'></asp:TextBox> 
                                    <asp:RegularExpressionValidator ID="txtValidateABNRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtABN"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="ABN can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                </EditItemTemplate> 
                                <FooterTemplate>
                                    <asp:TextBox Width="75%" ID="txtNewABN" runat="server" ></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="txtValidateNewABNRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtNewABN"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="ABN can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryAdd">*</asp:RegularExpressionValidator>
                                </FooterTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblABN" runat="server" Text='<%# Bind("abn") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="ACN" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top" SortExpression="acn"> 
                                <EditItemTemplate> 
                                    <asp:TextBox Width="75%" ID="txtACN" runat="server" Text='<%# Bind("acn") %>'></asp:TextBox> 
                                    <asp:RegularExpressionValidator ID="txtValidateACNRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtACN"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="ACN can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                </EditItemTemplate> 
                                <FooterTemplate>
                                    <asp:TextBox Width="75%" ID="txtNewACN" runat="server" ></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="txtValidateNewACNRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtNewACN"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="ACN can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryAdd">*</asp:RegularExpressionValidator>
                                </FooterTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblACN" runat="server" Text='<%# Bind("acn") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="BPay Account" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top" SortExpression="bpay_account"> 
                                <EditItemTemplate> 
                                    <asp:TextBox Width="75%" ID="txtBPayAccount" runat="server" Text='<%# Bind("bpay_account") %>'></asp:TextBox> 
                                    <asp:RegularExpressionValidator ID="txtValidateBPayAccountRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtBPayAccount"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="BPay Account can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                </EditItemTemplate> 
                                <FooterTemplate>
                                    <asp:TextBox Width="75%" ID="txtNewBPayAccount" runat="server" ></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="txtValidateNewBPayAccountRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtNewBPayAccount"
                                        ValidationExpression="^[0-9\-]+$"
                                        ErrorMessage="BPay Account can only be numbers and dashes."
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryAdd">*</asp:RegularExpressionValidator>
                                </FooterTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblBPay" runat="server" Text='<%# Bind("bpay_account") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Service Cycle (Weeks)" HeaderStyle-HorizontalAlign="Left" SortExpression="weeks_per_service_cycle" FooterStyle-VerticalAlign="Top" Visible="false"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlServiceCycle" runat="server" DataTextField="weeks_per_service_cycle" DataValueField="weeks_per_service_cycle"> </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblServiceCycle" runat="server" Text='<%# Eval("weeks_per_service_cycle") %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewServiceCycle" runat="server" DataTextField="weeks_per_service_cycle" DataValueField="weeks_per_service_cycle"> </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Free Services" HeaderStyle-HorizontalAlign="Left" SortExpression="free_services" FooterStyle-VerticalAlign="Top" Visible="false"> 
                                <EditItemTemplate> 
                                    <asp:DropDownList ID="ddlFreeServices" runat="server" DataTextField="free_services" DataValueField="free_services"> </asp:DropDownList> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblFreeServices" runat="server" Text='<%# Eval("free_services") %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                    <asp:DropDownList ID="ddlNewFreeServices" runat="server" DataTextField="free_services" DataValueField="free_services"> </asp:DropDownList>
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Start Date"  HeaderStyle-HorizontalAlign="Left" SortExpression="start_date" ItemStyle-CssClass="nowrap"> 
                                <EditItemTemplate> 
                                    <asp:TextBox ID="txtStartDate" runat="server" Text='<%# Eval("start_date", "{0:dd-MM-yyyy}") %>' />
                                    <asp:RegularExpressionValidator ID="txtValidateStartDateRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtStartDate"
                                        ValidationExpression="^\d{2}\-\d{2}\-\d{4}$"
                                        ErrorMessage="Start Date format must be dd-mm-yyyy"
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                    <asp:CustomValidator ID="txtValidateStartDate" runat="server"  CssClass="failureNotification"  
                                        ControlToValidate="txtStartDate"
                                        OnServerValidate="ValidStartDateCheck"
                                        ErrorMessage="Invalid Start Date"
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:CustomValidator>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblStartDate" runat="server" Text='<%# Eval("start_date", "{0:dd-MM-yyyy}") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="End Date"  HeaderStyle-HorizontalAlign="Left" SortExpression="end_date" ItemStyle-CssClass="nowrap"> 
                                <EditItemTemplate> 
                                    <asp:TextBox ID="txtEndDate" runat="server" Text='<%# Eval("end_date", "{0:dd-MM-yyyy}") %>' />
                                    <asp:RegularExpressionValidator ID="txtValidateEndDateRegex" runat="server" CssClass="failureNotification" 
                                        ControlToValidate="txtEndDate"
                                        ValidationExpression="^\d{2}\-\d{2}\-\d{4}$"
                                        ErrorMessage="End Date format must be dd-mm-yyyy"
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:RegularExpressionValidator>
                                    <asp:CustomValidator ID="txtValidateEndDate" runat="server"  CssClass="failureNotification"  
                                        ControlToValidate="txtEndDate"
                                        OnServerValidate="ValidEndDateCheck"
                                        ErrorMessage="Invalid End Date"
                                        Display="Dynamic"
                                        ValidationGroup="ValidationSummaryEdit">*</asp:CustomValidator>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblEndDate" runat="server" Text='<%# Eval("end_date", "{0:dd-MM-yyyy}") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Last Batch Run"  HeaderStyle-HorizontalAlign="Left" SortExpression="last_batch_run"> 
                                <EditItemTemplate> 
                                    <asp:Label ID="lblLastBatchRun" runat="server" Text='<%# Eval("last_batch_run", "{0:dd-MM-yyyy}") %>'></asp:Label>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblLastBatchRun" runat="server" Text='<%# Eval("last_batch_run", "{0:dd-MM-yyyy}") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="Date Added"  HeaderStyle-HorizontalAlign="Left" SortExpression="organisation_date_added" ItemStyle-CssClass="nowrap"> 
                                <EditItemTemplate> 
                                    <asp:Label ID="lblDateAdded" runat="server" Text='<%# Eval("organisation_date_added", "{0:dd-MM-yyyy}") %>'></asp:Label>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblDateAdded" runat="server" Text='<%# Eval("organisation_date_added", "{0:dd-MM-yyyy}") %>'></asp:Label>
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <%-- 
                            <asp:TemplateField HeaderText="Open Days"  HeaderStyle-HorizontalAlign="Left"> 
                                <EditItemTemplate> 
                                    <asp:Label ID="lblOpenDays" runat="server" Text='<%# (Eval("excl_sun").ToString()=="False"?"Sun<br/>":"") + (Eval("excl_mon").ToString()=="False"?"Mon<br/>":"") + (Eval("excl_tue").ToString()=="False"?"Tue<br/>":"") + (Eval("excl_wed").ToString()=="False"?"Wed<br/>":"") + (Eval("excl_thu").ToString()=="False"?"Thurs<br/>":"") + (Eval("excl_fri").ToString()=="False"?"Fri<br/>":"") + (Eval("excl_sat").ToString()=="False"?"Sat<br/>":"") %>'></asp:Label>
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblOpenDays" runat="server" Text='<%# (Eval("excl_sun").ToString()=="False"?"Sun<br/>":"") + (Eval("excl_mon").ToString()=="False"?"Mon<br/>":"") + (Eval("excl_tue").ToString()=="False"?"Tue<br/>":"") + (Eval("excl_wed").ToString()=="False"?"Wed<br/>":"") + (Eval("excl_thu").ToString()=="False"?"Thurs<br/>":"") + (Eval("excl_fri").ToString()=="False"?"Fri<br/>":"") + (Eval("excl_sat").ToString()=="False"?"Sat<br/>":"") %>'></asp:Label> 
                                </ItemTemplate> 
                            </asp:TemplateField> 
                            --%>

                            <asp:TemplateField HeaderText="Deleted" SortExpression="is_deleted" FooterStyle-VerticalAlign="Top"> 
                                <EditItemTemplate> 
                                    <asp:Label ID="lblIsDeleted" runat="server" Text='<%# Eval("is_deleted").ToString()=="True"?"Yes":"No" %>'></asp:Label> 
                                </EditItemTemplate> 
                                <ItemTemplate> 
                                    <asp:Label ID="lblIsDeleted" runat="server" Text='<%# Eval("is_deleted").ToString()=="True"?"Yes":"No" %>'></asp:Label> 
                                </ItemTemplate> 
                                <FooterTemplate> 
                                </FooterTemplate> 
                            </asp:TemplateField> 

                            <asp:TemplateField HeaderText="" ShowHeader="False" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top" > 
                                <EditItemTemplate> 
                                    <asp:LinkButton ID="lnkUpdate" runat="server" CausesValidation="True" CommandName="Update" Text="Update" ValidationGroup="ValidationSummaryEdit"></asp:LinkButton> 
                                    <asp:LinkButton ID="lnkCancel" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel"></asp:LinkButton> 
                                </EditItemTemplate> 
                                <FooterTemplate> 
                                    <asp:LinkButton ID="lnkAdd" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" ValidationGroup="ValidationSummaryAdd"></asp:LinkButton> 
                                </FooterTemplate> 
                                <ItemTemplate> 
                                   <asp:ImageButton ID="lnkEdit" runat="server" CommandName="Edit" ImageUrl="~/images/Inline-edit-icon-24.png"  AlternateText="Inline Edit" ToolTip="Inline Edit"/>
                                </ItemTemplate> 
                            </asp:TemplateField> 

                            <%--<asp:CommandField HeaderText="" ShowDeleteButton="True" ShowHeader="True" ButtonType="Image"  DeleteImageUrl="~/images/Delete-icon-24.png" />--%>

                            <asp:TemplateField HeaderText="" ShowHeader="True" HeaderStyle-HorizontalAlign="Left" FooterStyle-VerticalAlign="Top">
                                <ItemTemplate>
                                    <asp:ImageButton ID="btnDelete" runat="server"  CommandName="_Delete" CommandArgument='<%# Bind("organisation_id") %>' ImageUrl="~/images/Delete-icon-24.png" AlternateText="Delete" ToolTip="Delete" />
                                </ItemTemplate>
                            </asp:TemplateField>

                        </Columns> 

                    </asp:GridView>

                </div>
            </center>

        </div>
    </div>

</asp:Content>



