<%@ Page Title="Offering Popup Message" Language="C#" MasterPageFile="~/SiteV2.master" AutoEventWireup="true" CodeFile="TermsAndConditionsV2.aspx.cs" Inherits="TermsAndConditionsV2" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">

    <div class="clearfix">
        <div class="page_title"><asp:Label ID="lblHeading" runat="server">Terms & Conditions Of Use</asp:Label></div>
        <div class="main_content" style="padding:20px 5px;">

             <center>

                <asp:Label ID="lblErrorMessage" runat="server" ForeColor="Red" CssClass="failureNotification"></asp:Label>


                 <div style="text-align:left;">

<b>ENGLISH<br />
<br />
MEDICLINIC SOFTWARE LICENSE (End User License Agreement EULA)<br />
<br />
PLEASE READ THIS SOFTWARE LICENSE AGREEMENT ("LICENSE") CAREFULLY BEFORE USING THE MEDICLINIC SOFTWARE.  BY USING THE MEDICLINIC SOFTWARE, YOU ARE AGREEING TO BE BOUND BY THE TERMS OF THIS LICENSE. IF YOU DO NOT AGREE TO THE TERMS OF THIS LICENSE, DO NOT USE THE SOFTWARE. IF YOU DO NOT AGREE TO THE TERMS OF THE LICENSE, MEDICLINIC SOFTWARE WILL CEASE YOUR USE BY UNISTALLING ALL USE AND ACCESS.<br />
<br />
By use of the software, by your logging on and using the software you are deemed to agree to these terms and conditions in full.<br />
<br />
We promise that all data is safely stored in Australia on Australian hosted servers at all times.  SAFELY stored means the use of highest available encryption software as defined by industry standards.  Currently this is known as EV-A certificate encryption.<br />
<br />
IMPORTANT NOTE: This software may be used to reproduce materials. It is licensed to you only for reproduction of non-copyrighted materials, materials in which you own the copyright, or materials you are authorized or legally permitted to reproduce. This software may also be used for remote access to data files for listening between computers. Remote access of copyrighted data is only provided for lawful personal use or as otherwise legally permitted. If you are uncertain about your right to copy or permit access to any material you should contact your legal advisor. <br />
<br />
</b>


<b>1. General.</b> You may pay a fee for use of the Mediclinic Software or this may be provided to you free or as a trial.  All data remains your property at all times, You further agree that should any fee not be paid then you will go to “read only ”access after 7 days overdue and after 30 days overdue you will not have any access at all.  Overdue means the period after which payment requested has not been paid by you.  If no fee is paid or arrangements made in writing for collection of your data we will ARCHIVE the data for 3 years. The Mediclinic Software and any third party software, Vendor or Supplier, documentation and any fonts accompanying this License whether on disk, in read only memory, on any other media or in any other form (collectively the "Mediclinic Software") are licensed, not sold, to you by Mediclinic Software  ("Mediclinic Software ") for use only under the terms of this License, and Mediclinic Software  reserves all rights not expressly granted to you. The terms of this License will govern any software upgrades provided by Mediclinic Software that replace and/or supplement the original Mediclinic Software product, unless such upgrade is accompanied by a separate license in which case the terms of that license will govern.  The license period or term is defined as the period under which payment is current for use of the software or any free period of grace provided to the user at the discretion of mediclinic Software.<br />
<br />
Title and intellectual property rights in and to any content displayed by or accessed through the Mediclinic Software belongs to the respective content owner. Such content may be protected by copyright or other intellectual property laws and treaties, and may be subject to terms of use of the third party providing such content. This License does not grant you any rights to use such content.<br />
<br />
<b>2. Permitted License Uses and Restrictions.</b><br />
A. Subject to the terms and conditions of this License, you are granted a limited non-exclusive license to use the Mediclinic Software. The Mediclinic Software may be used to reproduce materials so long as such use is limited to reproduction of non-copyrighted materials, materials in which you own the copyright, or materials you are authorized or legally permitted to reproduce. Mediclinic Software is cloud based software accessible by a user name and password.  You will hold harmless Mediclinic Software, its employees agents or any other party associated with Mediclinic Software should these user names and passwords become available to unauthorised persons howsoever obtained. By use of our Cloud based software you accept any risk associated now or in the future with any such violation of the data. Mediclinic Software it agents staff, assignees or any party authorised by Mediclinic Software will not be held liable for any loss or damage howsoever caused.<br />
<br />
C. Mediclinic Software Updates- Automatic Updates. When you are using Mediclinic Software Updates, the Mediclinic Software will periodically check with Mediclinic Software for updates you will be responsible for ensuring that your data file is backed up PRIOR to installing any updates.  Mediclinic Software will not be liable for any loss, damage or misuse in any way of data damage in any way shape or form.<br />
<br />
<b>3. Transfer.</b> You may not rent, lease, lend, redistribute or sublicense the Mediclinic Software. The software is protected to allow only the number of persons to use the software as you have authorised.  This is done by passwords and user names.  You are held responsible for the safe keeping of same and fully indemnify Mediclinic Software Pty Ltd and all associated persons or assignees in every way.<br />
<br />
Updates: If an Mediclinic Software update completely replaces (full install) a previously licensed version of the Mediclinic Software , you may not use both versions of the Mediclinic Software at the same time nor may you transfer them separately.  Old versions will not be available.<br />
<br />
<b>4. Consent to Use.</b>  You agree that Mediclinic Software  and its subsidiaries may collect and use technical and related information, including but not limited to technical information about your computer, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support, security and other services to you (if any) related to the Mediclinic Software and to verify compliance with the terms of this License. Mediclinic Software may use this information, as long as it is in a form that does not personally identify you, to improve our products or to provide services or technologies to you.  You further agree that all of your data is held on a server operated by Mediclinic Software or its authorised representative or other party and this data may not be transferred and used elsewhere.  You further agree that should any fee not be paid then you will go to “read only ”access after 7 days overdue and after 30 days overdue you will not have any access at all.  Overdue means the period after which payment requested has not been paid by you.  You further agree that as you may have use to the data file at all times during the license period, and you may authorise others to use of the data file during a license period, Mediclinic Software can not and will not be held liable for corruption, loss or damage or sabotage in form to data integrity.<br />
<br />
You further agree to notify immediately by email to info@mediclinic.com.au of any person who is no longer authorised to use the system.  Mediclinic Software and all associated parties will not be held liable for any breach of security by your failure to notify us of any such person leaving your employ.<br />
<br />
<b>5. Other Services.</b> This software enables access to Mediclinic Software 's which offers downloads of data for sale and other services (collectively and individually, "Services"). Use of the Services requires Internet access and use of certain Services requires you to accept additional terms of service which will be presented to you before you can use such Services.<br />
<br />
By using this software in connection with an account, you agree to the latest Terms of Service, which you may access and review from MEDICLNIC Software if asked from time to time.<br />
<br />
You understand that by using any of the Services, you may encounter content that may be deemed offensive, indecent, or objectionable, which content may or may not be identified as having explicit language. Nevertheless, you agree to use the Services at your sole risk and that Mediclinic Software shall have no liability to you for content that may be found to be offensive, indecent, or objectionable. Content types (including genres, sub-genres and data categories and sub-categories and the like) and descriptions are provided for convenience, and you acknowledge and agree that Mediclinic Software does not guarantee their accuracy.<br />
<br />
Certain Services may include materials from third parties or links to certain third party web sites. You acknowledge and agree that Mediclinic Software is not responsible for examining or evaluating the content or accuracy of any such third-party material or web sites. Mediclinic Software does not warrant or endorse and does not assume and will not have any liability or responsibility for any third-party materials or web sites, or for any other materials, products, or services of third parties. Links to other web sites are provided solely as a convenience to you. You agree that you will not use any third-party materials in a manner that would infringe or violate the rights of any other party, and that Mediclinic Software is not in any way responsible for any such use by you.<br />
<br />
You agree that the Services, including but not limited to graphics, audio clips, and editorial content, contain proprietary information and material that is owned by Mediclinic Software and/or its licensors, and is protected by applicable intellectual property and other laws, including but not limited to copyright, and that you will not use such proprietary information or materials in any way whatsoever except for permitted use of the Services. No portion of the Services may be reproduced in any form or by any means. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Services, in any manner, and you shall not exploit the Services in any unauthorized way whatsoever, including but not limited to, by trespass or burdening network capacity. <br />
<br />
Mediclinic Software and its licensors reserve the right to change, suspend, remove, or disable access to any Services at any time without notice. In no event will Mediclinic Software be liable for the removal of or disabling of access to any such Services. Mediclinic Software may also impose limits on the use of or access to certain Services, in any case and without notice or liability. <br />
<br />
<b>6. Termination.</b> This License is effective until terminated. Your rights under this License will terminate automatically without notice from Mediclinic Software if you fail to comply with any term(s) of this License. Upon the termination of this License, you shall cease all use of the Mediclinic Software and destroy all copies, full or partial, of the Mediclinic Software.<br />
<br />
<b>7. Limited Warranty on Media.</b> Mediclinic Software warrants the media on which the Mediclinic Software is recorded and delivered by Mediclinic Software to be free from defects in materials and workmanship under normal use for a period of ninety (90) days from the date of original retail purchase. Your exclusive remedy under this Section shall be, at Mediclinic Software’s option, a refund of the purchase price of the product containing the Mediclinic Software or replacement of the Mediclinic Software which is returned to Mediclinic Software or Mediclinic Software authorized representative with a copy of the receipt. THIS LIMITED WARRANTY AND ANY IMPLIED WARRANTIES ON THE MEDIA INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND OF FITNESS FOR A PARTICULAR PURPOSE, ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF ORIGINAL RETAIL PURCHASE. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. THE LIMITED WARRANTY SET FORTH HEREIN IS THE ONLY WARRANTY MADE TO YOU AND IS PROVIDED IN LIEU OF ANY OTHER WARRANTIES (IF ANY) CREATED BY ANY DOCUMENTATION OR PACKAGING. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY BY JURISDICTION.<br />
<br />
<b>8. Disclaimer of Warranties.</b> YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE MEDICLINIC SOFTWARE (AS DEFINED ABOVE) AND SERVICES (AS DEFINED BELOW) IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. EXCEPT FOR THE LIMITED WARRANTY ON MEDIA SET FORTH ABOVE AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE MEDICLINIC SOFTWARE AND SERVICES ARE PROVIDED "AS IS", WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND MEDICLINIC SOFTWARE  AND MEDICLINIC SOFTWARE 'S LICENSORS (COLLECTIVELY REFERRED TO AS "MEDICLINIC SOFTWARE " FOR THE PURPOSES OF SECTIONS 8 AND 9) HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE MEDICLINIC SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS. MEDICLINIC SOFTWARE DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE MEDICLINIC SOFTWARE OR SERVICES THAT THE FUNCTIONS CONTAINED IN THE MEDICLINIC SOFTWARE OR SERVICES WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE MEDICLINIC SOFTWARE OR SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE MEDICLINIC SOFTWARE OR SERVICES WILL BE CORRECTED. YOU FURTHER ACKNOWLEDGE THAT THE MEDICLINIC SOFTWARE IS NOT INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE OF, OR ERRORS OR INACCURACIES IN THE CONTENT, DATA OR INFORMATION PROVIDED BY, THE MEDICLINIC SOFTWARE COULD LEAD TO DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE, INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR WEAPONS SYSTEMS. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY MEDICLINIC SOFTWARE OR AN MEDICLINIC SOFTWARE AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE MEDICLINIC SOFTWARE OR SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.  <br />
<br />
<b>9. Limitation of Liability.</b> TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL MEDICLINIC SOFTWARE  BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE MEDICLINIC SOFTWARE OR SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF MEDICLINIC SOFTWARE  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Mediclinic Software’s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.<br />
<br />
<b>10. Export Control.</b> You may not use or otherwise export or re exports the Mediclinic Software   except as authorized by Australian law and the laws of the jurisdiction in which the Mediclinic Software   was obtained. In particular, but without limitation, the Mediclinic Software   may not be exported or re-exported (a) into any AUSTRALIAN embargoed countries or (b) to anyone on the AUSTRALIAN Treasury Department's list of Specially Designated Nationals or the AUSTRALIAN Department of Commerce Denied Person’s List or Entity List. By using the Mediclinic Software, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use these products for any purposes prohibited by Australian law, including, without limitation, the development, design, manufacture or production of missiles, or nuclear, chemical or biological weapons.<br />
<br />
<b>11. Controlling Law and Severability.</b> This License will be governed by and construed in accordance with the laws of the Australia, as applied to agreements entered into and to be performed entirely within Australia between Australia residents. This License shall not be governed by the United Nations Convention on Contracts for the International Sale of Goods, the application of which is expressly excluded. If for any reason a court of competent jurisdiction finds any provision, or portion thereof, to be unenforceable, the remainder of this License shall continue in full force and effect.<br />
<br />
<b>12. Third Party Software.</b>  By use of Mediclinic Software and any third party Software, for example Eclaims, OMNIS, Microsoft or any other software used by Mediclinic Software, which may have their own separate license agreements and terms, OMNIS, Microsoft or any other software used by Mediclinic Software, which may have their own separate license agreements and terms, you agree that Mediclinic Software is in no way liable for any loss, damage, misuse or any other hazard which may have occurred by use of Mediclinic Software.<br />
<br />
<b>13. PAYMENT of FEES.</b> You agree to pay the fees as charge to you from time to time that should you fail to pay the license fee requested in full including any third party access fees charged by Mediclinic Software to you by the 7th orf each consecutive month, then Mediclinic Software has the right to disable your access to any server or computer or data file for update or any amendment whatsoever until full payment has been made and cleared by the bankers of mediclinic Software.  Restored use is at the sole discretion of Mediclinic Software.<br />
<br />
<b>13. Complete Agreement; Governing Language.</b> This License constitutes the entire agreement between the parties with respect to the use of the Mediclinic Software licensed hereunder and supersedes all prior or contemporaneous understandings regarding such subject matter, with the exception of any additional terms and conditions you are required to accept if you choose to use Mediclinic Software's online store which will govern your use of such store and any Services you purchase through that store. No amendment to or modification of this License will be binding unless in writing and signed by Mediclinic Software. Any translation of this License is done for local requirements and in the event of a dispute between the English and any non-English versions, the English version of this License shall govern.<br />
<br />
<b>14. Third Party Acknowledgements and Terms.</b> Portions of the Mediclinic Software utilize or include third party software and other copyrighted material. Acknowledgements, licensing terms and additional disclaimers for such material are contained in the “online” electronic documentation for the Mediclinic Software or may otherwise accompany such material, and your use of such material is governed by their respective terms. <br />
<br />
Mediclinic Software is not obligated to provide you with new enhanced or additional data types or categories that Mediclinic Software may provide in the future and is free to discontinue its services at any time. MEDICLINIC SOFTWARE DISCLAIMS ALL WARRANTIES EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.  MEDICLINIC SOFTWARE DOES NOT WARRANT THE RESULTS THAT WILL BE OBTAINED BY YOUR USE OF THE MEDICLINIC SOFTWARE OR ANY MEDICLINIC SOFTWARE SERVER. IN NO CASE WILL MEDICLINIC SOFTWARE IS LIABLE FOR ANY CONSEQUENTIAL OR INCIDENTAL DAMAGES OR FOR ANY LOST PROFITS OR LOST REVENUES. <br />
<br />
<br />
Without limiting the foregoing, under no circumstances shall Mediclinic Software  be held liable for any delay or failure in performance resulting directly or indirectly from acts of nature, forces, or causes beyond its reasonable control, including, without limitation, Internet failures, computer equipment failures, telecommunication equipment failures, other equipment failures, electrical power failures, strikes, labour disputes, riots, insurrections, civil disturbances, shortages of labour or materials, fires, floods, storms, explosions, acts of God, war, governmental actions, orders of domestic or foreign courts or tribunals, non-performance of third parties, or loss of or fluctuations in heat, light, or air conditioning. <br />
<br />
<b>Miscellaneous Provisions.</b> This license agreement will be governed by and construed in accordance with the laws of the Australia, without giving effect to its conflict of laws provisions or your actual state or country of residence. If for any reason a court of competent jurisdiction finds any provision or portion of the TOS to be unenforceable, the remainder of the TOS will continue in full force and effect. <br />
<br />
This license agreement constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. Any waiver of any provision of the License Agreement will be effective only if in writing and signed by Mediclinic Software.<br />
<br />
Mediclinic Software is owned by Carepro (IT) Pty Ltd and any reference to Mediclinic Software implies referral and reference to Carepro (IT) Pty ltd, it’s heirs, successors or assigns or suppliers and partners.<br />

                 </div>


            </center>

        </div>
    </div>


</asp:Content>



