
<div style="display: none;" class="contextMenu" id="myMenu1">
    <ul>
        <li id="open"> Open</li>
        <li id="email">Email</li>
        <li id="save">Save</li>
        <li id="delete">Delete</li>
    </ul>
</div>

<div style="display: none;" class="contextMenu" id="myMenu2">
    <ul>
        <li id="item_11">Item 1</li>
        <li id="item_12">Item 2</li>
        <li id="item_13">Item 3</li>
        <li id="item_14">Item 4</li>
        <li id="item_15">Item 5</li>
        <li id="item_16">Item 6</li>
        <li id="item_17">Item 7</li>
        <li id="item_18">Item 8</li>
    </ul>
</div>

<div style="display: none;" class="contextMenu" id="myMenu3">
    <ul>
        <li id="item_1">Item 1</li>
        <li id="item_2">Item 2</li>
        <li id="item_3">Item 3</li>
    </ul>
</div>


<div style="display: none;"  class="contextMenu" id="myMenuA">
    <ul>
        <li id="email">E-mail</li>
        <li id="homepage">Homepage</li>
    </ul>
</div>

